# Generated by Django 3.2.20 on 2025-02-15 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positionName', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('salary', models.FloatField()),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'python_jobs',
            },
        ),
    ]
